name: Deploy Book

on:
  push:
    branches:
      - main
      - vk-graph # TEMP
    paths-ignore:
      - "bin/**"
      - "examples/**"

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read
      pages: write  # To push to a GitHub Pages site
      id-token: write # To update the deployment status
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - name: Install mdBook
        run: cargo install --locked mdbook --version 0.5.3

      - name: Build Book
        run: |
          cd guide
          mdbook build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'guide/book'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
